# Generated by Django 5.2.7 on 2025-10-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Nhóm')),
            ],
            options={
                'verbose_name': 'Nhóm',
                'verbose_name_plural': 'Các Nhóm',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=50, verbose_name='Họ')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('groups', models.ManyToManyField(blank=True, related_name='contacts', to='contacts.group', verbose_name='Thuộc Nhóm')),
            ],
            options={
                'verbose_name': 'Liên hệ',
                'verbose_name_plural': 'Các Liên hệ',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
